packaging_format = 2

id = "statpingng"
name = "statping-ng"
description.en = "External monitoring tool"
description.fr = "Outils de monitoring externe"

version = "0.90.80~ynh1"

maintainers = ["oiseauroch"]

[upstream]
license = "GPL-3.0-only"
website = "https://statping-ng.github.io/"
admindoc = "https://github.com/statping-ng/statping-ng/wiki"
userdoc = "https://statping-ng.github.io/"
code = "https://github.com/statping-ng/statping-ng/"

[integration]
yunohost = ">= 11.1.20"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "string"
    choices = ["fr", "en", "es", "ru", "de", "cs", "ja", "ko", "it", "zh"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Choose an admin password"
    help.fr = "Choisissez une phrase de passe pour l'administrateur."
    type = "password"

[resources]

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"
