packaging_format = 2

id = "statpingng"
name = "statping-ng"
description.en = "External monitoring tool"
description.fr = "Outils de monitoring externe"

version = "0.91.0~ynh1"

maintainers = ["oiseauroch"]

[upstream]
license = "GPL-3.0-only"
website = "https://statping-ng.github.io/"
admindoc = "https://github.com/statping-ng/statping-ng/wiki"
userdoc = "https://statping-ng.github.io/"
code = "https://github.com/statping-ng/statping-ng/"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "150M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en", "es", "ru", "de", "cs", "ja", "ko", "it", "zh"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    amd64.url = "https://github.com/statping-ng/statping-ng/releases/download/v0.91.0/statping-linux-amd64.tar.gz"
    amd64.sha256 = "0f748cf32b27c7125d73851096db24fd3136990a2fd530387d6757562eb798b4"
    arm64.url = "https://github.com/statping-ng/statping-ng/releases/download/v0.91.0/statping-linux-arm64.tar.gz"
    arm64.sha256 = "d6952e66fe5f4fec2f10fb35a87634b151bf12403397e4bd131517420a9b6e82"
    i386.url = "https://github.com/statping-ng/statping-ng/releases/download/v0.91.0/statping-linux-386.tar.gz"
    i386.sha256 = "d50773ebdd2769693ee01a55266a66726bf9a0df7f29a27cf555c16aa8d358cc"
    armhf.url = "https://github.com/statping-ng/statping-ng/releases/download/v0.91.0/statping-linux-arm-7.tar.gz"
    armhf.sha256 = "850d1a20cd0502b06c39ad1433204f3076e616a95d2b984395f593d2f0f52c9f"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^statping-linux-amd64.tar.gz$"
    autoupdate.asset.arm64 = "^statping-linux-arm64.tar.gz$"
    autoupdate.asset.i386 = "^statping-linux-386.tar.gz$"
    autoupdate.asset.armhf = "^statping-linux-arm-7.tar.gz$"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"
